// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3qjbZl-THaGUX_grFmXcjFp_VN8qFt4I',
    appId: '1:556706045177:web:3d4ce6f241c6b48334d628',
    messagingSenderId: '556706045177',
    projectId: 'wellfoundapplicatio',
    authDomain: 'wellfoundapplicatio.firebaseapp.com',
    storageBucket: "wellfoundapplicatio.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmIXuBmsHlUc4jpWuzjga5LHIByP_ZYJE',
    appId: '1:556706045177:android:3f4c3de9d480215334d628',
    messagingSenderId: '556706045177',
    projectId: 'wellfoundapplicatio',
    storageBucket: 'wellfoundapplicatio.appspot.com',
  );
}
